### Numpy - Numerical Python

Advantages of Numpy Arrays:
1. Allows several Mathematical Operations
2. Faster operations

In [5]:
import numpy as np

#### List vs Numpy - Time Taken

In [6]:
from time import process_time

Time taken by a list

In [8]:
python_list = [i for i in range(1000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)   # 0.000218713000002424

0.0


In [9]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array += 5

end_time = process_time()

print(end_time - start_time)   # 0.00015789400000087994

0.0


## Numpy Arrays

In [10]:
# list
list1 = [1,2,3,4,5]

print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [11]:
# creating a 1 dim array
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [12]:
a.shape

(4,)

In [13]:
b = np.array([(1,2,3,4), (5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [14]:
b.shape

(2, 4)

In [15]:
c = np.array([(1,2,3,4), (5,6,7,8)], dtype=float)

print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial Placeholders in numpy arrays

In [17]:
# create a numpy array of Zeros
x = np.zeros((4,5), dtype=int)
print(x)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [18]:
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [19]:
# array of a particular value
z = np.full((5,4),4)
print(z)

[[4 4 4 4]
 [4 4 4 4]
 [4 4 4 4]
 [4 4 4 4]
 [4 4 4 4]]


In [23]:
# create an identity matrix
a = np.eye(4, dtype=int)
print(a)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [31]:
# create a numpy array with random values
b = np.random.random((3,4))

In [32]:
print(b)

[[0.14625821 0.3753761  0.29455935 0.16591444]
 [0.79794238 0.21779057 0.70560649 0.4141842 ]
 [0.33527064 0.05524604 0.99185785 0.12790797]]


In [33]:
# random integer values array within a specific range
c = np.random.randint(10, 100, (3,5))
print(c)

[[16 60 72 41 35]
 [56 33 27 46 46]
 [37 49 34 58 98]]


In [36]:
# array of evenly saced values --> specifying the number of values required
d = np.linspace(10, 30, 6)
print(d)

[10. 14. 18. 22. 26. 30.]


In [40]:
# array of evenly spaced values --> specifying the step
e = np.arange(10, 30, 5)
print(e)

[10 15 20 25]


In [41]:
# convert a list to a numpy array
list2 = [10,20,20,20,50]

np_array = np.array(list2)
print(np_array)
type(np_array)

[10 20 20 20 50]


numpy.ndarray

Analysing a numpy array

In [44]:
c = np.random.randint(10, 90, (5,5))
print(c)

[[13 71 11 34 16]
 [34 21 67 48 73]
 [42 82 41 26 10]
 [64 51 86 19 86]
 [67 17 73 33 72]]


In [45]:
# array dimension
print(c.shape)

(5, 5)


In [46]:
# number of dimentions
print(c.ndim)

2


In [47]:
# number of elements in an array
print(c.size)

25


In [48]:
# checking the data types of the values in the array
print(c.dtype)

int32


## Mathematical operations on a np array

In [49]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [50]:
a = np.random.randint(0, 10, (3,3))
b = np.random.randint(10, 20, (3,3))

print(a)
print(b)

[[8 9 2]
 [9 1 8]
 [1 8 8]]
[[16 19 12]
 [14 18 16]
 [14 11 19]]


In [52]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[24 28 14]
 [23 19 24]
 [15 19 27]]
[[ -8 -10 -10]
 [ -5 -17  -8]
 [-13  -3 -11]]
[[128 171  24]
 [126  18 128]
 [ 14  88 152]]
[[0.5        0.47368421 0.16666667]
 [0.64285714 0.05555556 0.5       ]
 [0.07142857 0.72727273 0.42105263]]


In [53]:
a = np.random.randint(0, 10, (3,3))
b = np.random.randint(10, 20, (3,3))

In [54]:
print(a)
print(b)

[[0 5 6]
 [6 9 0]
 [1 3 5]]
[[19 12 19]
 [19 17 10]
 [17 19 18]]


In [57]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[19 17 25]
 [25 26 10]
 [18 22 23]]
[[-19  -7 -13]
 [-13  -8 -10]
 [-16 -16 -13]]
[[  0  60 114]
 [114 153   0]
 [ 17  57  90]]
[[0.         0.41666667 0.31578947]
 [0.31578947 0.52941176 0.        ]
 [0.05882353 0.15789474 0.27777778]]


## Array Manipulation

In [58]:
array = np.random.randint(0, 10, (2,3))
print(array)
print(array.shape)

[[8 7 9]
 [5 6 5]]
(2, 3)


In [63]:
# transpose

trans = np.transpose(array)
print(trans)
print(trans.shape)

[[8 5]
 [7 6]
 [9 5]]
(3, 2)


In [65]:
array = np.random.randint(0, 10, (2,3))
print(array)
print(array.shape)

[[6 1 2]
 [8 0 9]]
(2, 3)


In [66]:
trans2 = array.T
print(trans2)
print(trans2.shape)

[[6 8]
 [1 0]
 [2 9]]
(3, 2)


In [67]:
# reshaping an array

a = np.random.randint(0, 10, (2,3))
print(a)
print(a.shape)

[[1 9 9]
 [3 2 8]]
(2, 3)


In [68]:
b = a.reshape(3,2)

In [69]:
b

array([[1, 9],
       [9, 3],
       [2, 8]])