## Numpy

In [5]:
import numpy as np

In [6]:
np.absolute(-5)

5

In [7]:
a = np.array([1,2,3,4])

In [8]:
type(a)

numpy.ndarray

In [9]:
a.shape

(4,)

In [10]:
b = np.array([[1,2,3,4], [5,6,7,8]])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [11]:
print(b.shape)

(2, 4)


In [12]:
#transepose
b.T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [13]:
#dot_Product
np.dot(b,b.T)

array([[ 30,  70],
       [ 70, 174]])

In [14]:
#check
np.random.randint?

In [15]:
#randint(low, high=None, size=None, dtype=int)
np.random.randint(60, 100,10)

array([82, 72, 78, 86, 72, 63, 77, 74, 74, 72])

In [16]:
matrix = np.random.randint(60, 100,(5,5))

In [17]:
matrix

array([[87, 64, 82, 71, 79],
       [83, 88, 83, 90, 80],
       [96, 88, 64, 98, 85],
       [78, 94, 77, 83, 91],
       [87, 85, 89, 77, 91]])

In [18]:
np.max(matrix)

98

In [19]:
np.min(matrix)

64

In [20]:
a = np.array([0,1,2,-8,6,8,-10])

In [21]:
#index of minimum in an array
np.argmin(a)

6

In [22]:
b = np.array([0,0,1,1,1,2,3,4,4,5])

In [23]:
#generates unique values in an array
np.unique(b)

array([0, 1, 2, 3, 4, 5])

In [24]:
c, counts = np.unique(b, return_counts=True)

In [25]:
c

array([0, 1, 2, 3, 4, 5])

In [26]:
counts

array([2, 3, 1, 1, 2, 1], dtype=int64)

### Program to find out the number with the highest frequency in the number

In [27]:
d = np.unique(b, return_counts=True)

In [28]:
d

(array([0, 1, 2, 3, 4, 5]), array([2, 3, 1, 1, 2, 1], dtype=int64))

In [30]:
index = np.argmax(d[1]) #index with highest freq
ele = d[0][index]
print(ele)

1


## Slicing Array

In [31]:
matrix

array([[87, 64, 82, 71, 79],
       [83, 88, 83, 90, 80],
       [96, 88, 64, 98, 85],
       [78, 94, 77, 83, 91],
       [87, 85, 89, 77, 91]])

In [32]:
# start: end+1
matrix[2:4, 1:4]

array([[88, 64, 98],
       [94, 77, 83]])

In [34]:
matrix[:, 3:]

array([[71, 79],
       [90, 80],
       [98, 85],
       [83, 91],
       [77, 91]])